---
title: "week2"
author: "vamsikrishnakakani"
date: "January 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Sequences of Numbers}
a<- 1:35
a
```

```{r Vectors}
a <- c("school", 1 ,2 ,3 ,4 ,"total","records")
a
a <- c("omaha",16,16,8,30,"70","6-11,1-4")
a
a<- c("western",22,18,22,16,"78","7-12,3-3")
a
x<- c(16,16,8,30)
y<- c(22,18,22,16)
x
y
```

```{r Missing Values}
x<- c(16,16,8,30)
y<- c(22,18,22,16)
is.na(x)
a<- c("western",22,18,22,16,"78","7-12,3-3")
is.na(a)
a <- c(NA,16,16,8,30,"70","6-11,1-4")
is.na(a)
b<- c(18, 12,37, 7,NA, NaN, 2)
is.na(b)
is.nan(b)

```

```{r Subsetting Vector}
x<- c(16,16,8,30)
y<- c(22,18,22,16)
subset(x,x>9,drop=FALSE)
subset(y,y<10,drop=FALSE)
x[2:4]
y[1:1]
x[-c(2,2)]
y[-c(3)]
y[-c(2,3)]
```

```{r  Matrices and Data Frame}
rownames=c("omaha","WIU")
colnames=c("1","2","3","4","Total")
m1 <- matrix(c(16,22,16,18,8,22,30,16,70,78),nrow = 2,ncol = 5 , dimnames = list(rownames, colnames))
print(m1)
df<- data.frame(universities=c("omaha","WIU"), one =c(16,22), two=c(16,18), three=
c(8,22), four=c(30,16),total=c(70,78),stringsAsFactors = FALSE)
df
```
